version: "3"
services:
  squid_web:
    image: nginx:latest
    container_name: squid_web
    volumes:
      - ./docker/squid.du.crt:/etc/nginx/ssl/squid.du.crt
      - ./docker/squid.du.key:/etc/nginx/ssl/squid.du.key
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  squid_app:
    image: squid_app
    container_name: squid_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/squid
    depends_on:
      - squid_web
    ports:
      - 8080:8080