version: "3"
services:
  squid_web:
    image: nginx:latest
    container_name: squid_web
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - squid_app
  squid_app:
    image: squid_app
    container_name: squid_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/squid
    ports:
      - 8087:8080