export const articleData = [
	{
		typeDetail: "DATA SET",
		symbol: "QUICRA-0",
		title: "🖼 DataUnion.app - Image & Annotation Vault 📸",
		publishier: "🤝 DataUnion.app",
		content: "Notice This dataset and the software stack behind it are under constant development. Check our Twitter for …",
		price: "759.519",
		network: "ETH",
	},
	{
		typeDetail: "DATA SET",
		symbol: "LUMSTA-42",
		title: "Product Pages of 1’044’709 Products on Amazon.com (p…",
		publishier: "🦄 Innovation Atelier SA",
		content: "Result of scraping of Amazon.com product page data over H1 2018, obtained using neutral profile/IP address. …",
		price: "113,927.857",
		network: "ETH",
	},
	{
		typeDetail: "DATA SET",
		symbol: "EXCANE-93",
		title: "EVO/2MP/TRFC/DE/200K Weekly Collector",
		publishier: "👁️ Evotegra GmbH",
		content: "Evotegra - EVO/2MP/TRFC/DE/200K German Traffic Data for Machine Learning rugpullindex.com rank Badge…",
		price: "1,216.163",
		network: "ETH",
	},
	{
		typeDetail: "DATA SET",
		symbol: "TREPEL-36",
		title: "Data Whale Ocean Marketplace Directory & Po…",
		publishier: "🐳 Data Whale Curation & Management",
		content: "The Directory provides you with valuable insights to the top Data Token liquidity pools on the Ocean Protoco…",
		price: "60.249",
		network: "ETH",
	},
	{
		typeDetail: "DATA SET",
		symbol: "TASLOB-45",
		title: "Swash - Consumer Browsing Data",
		publishier: "SwashData Tech Oy",
		content: "Swash is creating the world’s first Data Union. It crowdsources users’ surfing data through a browser plugin (…",
		price: "14,546.01",
		network: "ETH",
	},
	{
		typeDetail: "DATA SET",
		symbol: "WONPEL-82",
		title: "Ocean Market 🌊 Pool trends and charts 📈",
		publishier: "📊 Bridging.tech Datasets",
		content: "Dataset This 'pool trends and charts' dataset offers insights in the hourly activity for popular data pools listed i…",
		price: "26.689",
		network: "ETH",
	},
	{
		typeDetail: "DATA SET",
		symbol: "EXCWHA-70",
		title: "eBay DATASET - 10 Million Data Points (1,000,000 Prod…",
		publishier: "🗄️ Data Reservoir",
		content: "alt text This dataset has a massive total of over 10 million data points from over 1, 000, 000 product listings on e…",
		price: "1,006.121",
		network: "ETH",
	},
	{
		typeDetail: "DATA SET",
		symbol: "GENFUG-26",
		title: "Swash - Data Analytics and Insights",
		publishier: "SwashData Tech Oy",
		content: "This asset is dedicated to productised data analytics from the Swash data set.The liquidity balance in this po…",
		price: "267.024",
		network: "ETH",
	}]